[package]
name = "tidy-tree"
version = "0.1.1"
edition = "2021"
license = "MIT"
include = ["Cargo.toml", "**/*.rs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
